name: respy_estimagic
   
dependencies:
  - python=3.6
  - numpy
  - pandas=0.23.4
  - statsmodels
  - pytest
  - pytest-xdist
  - scipy
  - flake8
  - matplotlib
  - jupyter
  - jupyterlab
  - pip:
    - Py-BOBYQA
    - DFO-LS
    - mpi4py
